name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build Spring Boot backend
        working-directory: ./devkin
        run: ./mvnw clean package -DskipTests

      - name: Build React frontend
        working-directory: ./devkin-frontend
        run: npm install && npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: |
          docker build -t your-dockerhub-username/backend ./devkin
          docker build -t your-dockerhub-username/frontend ./devkin-frontend

      - name: Push Docker images
        run: |
          docker push your-dockerhub-username/backend
          docker push your-dockerhub-username/frontend

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve \
          -var "docker_image_frontend=your-dockerhub-username/frontend" \
          -var "docker_image_backend=your-dockerhub-username/backend" \
          working-directory: ./terraform
